version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventNet
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
